version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - c8:b5:62:a8:54:dc:2f:39:30:0e:68:49:40:d5:d3:8b
      - checkout
      - run: npm install
      - run: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Lint runs on every push (including tags)
      - lint:
          filters:
            tags:
              only: /^v.*/
      # Deploy docs from master or a tag
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
