version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - 3c:57:3c:f2:f2:f3:b9:3b:9d:eb:80:0c:3e:2b:20:1d
      - checkout
      - run: npm install
      - run: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Lint runs on every push (including tags)
      - lint:
          filters:
            tags:
              only: /^v.*/
      # Deploy docs from master or a tag
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
